// Imports the PWA's baked campaign levels (../js/core/baked.js) verbatim into
// lib/core/baked_levels.dart. Run from mobile/: dart run tool/import_pwa_levels.dart
import 'dart:io';

void main() {
  final src = File('../js/core/baked.js');
  if (!src.existsSync()) {
    stderr.writeln('Cannot find ${src.path}. Run from the mobile/ directory.');
    exit(1);
  }
  final entry = RegExp(r'^\s*(\d+):\s*("(?:[^"\\]|\\.)*"),\s*$', multiLine: true);
  final out = StringBuffer()
    ..writeln('// AUTO-GENERATED by tool/import_pwa_levels.dart from js/core/baked.js — do not edit.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln('const Map<int, String> bakedLevels = {');
  var count = 0;
  for (final m in entry.allMatches(src.readAsStringSync())) {
    final value = m.group(2)!.replaceAll(r'$', r'\$').replaceAll("'", r"\'");
    out.writeln("  ${m.group(1)}: '${value.substring(1, value.length - 1)}',");
    count++;
  }
  out.writeln('};');
  File('lib/core/baked_levels.dart').writeAsStringSync(out.toString());
  stdout.writeln('Imported $count levels -> lib/core/baked_levels.dart');
}
