// Generates ios/Flutter/AdMob-{Debug,Release}.xcconfig from config/admob.json so the
// iOS GADApplicationIdentifier (Info.plist → $(ADMOB_APP_ID)) comes from the same
// single source of truth as Android and Dart. Run from mobile/ after editing the JSON:
//   dart run tool/sync_admob_config.dart
import 'dart:convert';
import 'dart:io';

void main() {
  final json = jsonDecode(File('config/admob.json').readAsStringSync()) as Map<String, dynamic>;
  String iosAppId(String section) => ((json[section] as Map)['ios'] as Map)['appId'] as String;

  void write(String file, String section, String appId) {
    File(file).writeAsStringSync('''
// AUTO-GENERATED by tool/sync_admob_config.dart from config/admob.json ("$section") — do not edit.
ADMOB_APP_ID = $appId
''');
    stdout.writeln('wrote $file ($appId)');
  }

  write('ios/Flutter/AdMob-Debug.xcconfig', 'test', iosAppId('test'));
  final release = iosAppId('release');
  write('ios/Flutter/AdMob-Release.xcconfig', 'release', release);
  if (release.contains('REPLACE')) {
    stdout.writeln('NOTE: iOS release AdMob IDs are placeholders — ads stay disabled on iOS release builds '
        'until real IDs are set in config/admob.json.');
  }
}
