// Pre-generates every procedural campaign level into js/core/baked.js so the
// game never has to run the generator (and its solver verification) on-device.
// Usage: npm run build
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { LEVEL_COUNT, paramsFor } from '../js/core/levels.js';
import { generateLevel } from '../js/core/generator.js';
import { HANDCRAFTED } from '../js/core/handcrafted.js';
import { encodeLevel } from '../js/core/codec.js';

const out = {};
const t0 = Date.now();
for (let n = 1; n <= LEVEL_COUNT; n++) {
  if (HANDCRAFTED[n]) continue;
  out[n] = encodeLevel(generateLevel(paramsFor(n)));
}
const file = fileURLToPath(new URL('../js/core/baked.js', import.meta.url));
const body = Object.entries(out).map(([n, s]) => `  ${n}: ${JSON.stringify(s)},`).join('\n');
writeFileSync(
  file,
  `// AUTO-GENERATED by scripts/bake.mjs — do not edit by hand.\nexport const BAKED = {\n${body}\n};\n`,
);
console.log(`Baked ${Object.keys(out).length} levels in ${Date.now() - t0}ms -> js/core/baked.js`);
